# Generated by Django 5.0.6 on 2024-06-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('SUSTRATOS', 'Sustratos'), ('MACETEROS', 'Maceteros'), ('FLORES', 'Flores'), ('SUCULENTAS', 'Suculentas'), ('TIERRA DE HOJA', 'Tierra de hoja')], max_length=25),
        ),
    ]
