# Generated by Django 5.0.6 on 2024-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0002_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('MACETEROS', 'Maceteros'), ('SUSTRATOS', 'Sustratos'), ('FLORES', 'Flores'), ('SUCULENTAS', 'Suculentas')], max_length=25),
        ),
    ]
