# Generated by Django 5.0.6 on 2024-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0003_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MACETEROS', 'Maceteros'), ('SUCULENTAS', 'Suculentas'), ('OTRO', 'Otro'), ('SUSTRATOS', 'Sustratos'), ('FLORES', 'Flores'), ('TIERRA DE HOJA', 'Tierra de hoja')], max_length=25),
        ),
    ]
