# Generated by Django 5.0.6 on 2024-06-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0004_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('FLORES', 'Flores'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('SUCULENTAS', 'Suculentas'), ('SUSTRATOS', 'Sustratos'), ('MACETEROS', 'Maceteros')], max_length=25),
        ),
    ]
