# Generated by Django 5.0.6 on 2024-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0006_alter_producto_tipo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('SUCULENTAS', 'Suculentas'), ('SUSTRATOS', 'Sustratos'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('FLORES', 'Flores'), ('MACETEROS', 'Maceteros')], max_length=25),
        ),
    ]
