# Generated by Django 5.0.6 on 2024-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0007_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MACETEROS', 'Maceteros'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('OTRO', 'Otro'), ('SUSTRATOS', 'Sustratos'), ('SUCULENTAS', 'Suculentas'), ('FLORES', 'Flores')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
