# Generated by Django 5.0.6 on 2024-07-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0008_alter_producto_tipo_alter_user_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MACETEROS', 'Maceteros'), ('SUCULENTAS', 'Suculentas'), ('OTRO', 'Otro'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('SUSTRATOS', 'Sustratos'), ('FLORES', 'Flores')], max_length=25),
        ),
    ]
